"""Prometheus metrics and structured lifecycle logging for the server."""

from __future__ import annotations

import json
import logging
from logging.handlers import QueueHandler, QueueListener
from queue import SimpleQueue
from typing import Any, Dict, Optional

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram, make_asgi_app

from engine.scheduler import Request
from engine.telemetry import SchedulerSnapshot


_DURATION_BUCKETS = (
    0.001,
    0.005,
    0.01,
    0.025,
    0.05,
    0.1,
    0.25,
    0.5,
    1,
    2.5,
    5,
    10,
    30,
    60,
)
_ITL_BUCKETS = (0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5)
_BATCH_BUCKETS = (1, 2, 4, 8, 16, 32, 64, 128)
_LOG_LISTENER: Optional[QueueListener] = None


class JsonLogFormatter(logging.Formatter):
    """Serialize only explicit, privacy-reviewed telemetry fields."""

    def format(self, record: logging.LogRecord) -> str:
        payload: Dict[str, Any] = {
            "timestamp": self.formatTime(record, "%Y-%m-%dT%H:%M:%S%z"),
            "level": record.levelname,
            "logger": record.name,
            "event": getattr(record, "event", "log"),
        }
        payload.update(getattr(record, "telemetry_fields", {}))
        return json.dumps(payload, separators=(",", ":"), sort_keys=True)


def configure_json_logging(level: int = logging.INFO) -> logging.Logger:
    """Configure non-blocking JSON lifecycle logging once."""

    global _LOG_LISTENER
    logger = logging.getLogger("mini_vllm.telemetry")
    logger.setLevel(level)
    if not logger.handlers:
        queue = SimpleQueue()
        output = logging.StreamHandler()
        output.setFormatter(JsonLogFormatter())
        logger.addHandler(QueueHandler(queue))
        _LOG_LISTENER = QueueListener(queue, output, respect_handler_level=True)
        _LOG_LISTENER.start()
    logger.propagate = False
    return logger


class PrometheusTelemetry:
    """Thread-safe metric sink used by the single engine worker.

    Every instance owns a registry. Tests and multiple apps can therefore be
    created in one process without duplicate metric registration.
    """

    def __init__(
        self,
        model_name: str,
        *,
        registry: Optional[CollectorRegistry] = None,
        logger: Optional[logging.Logger] = None,
    ) -> None:
        self.model_name = model_name
        self.registry = registry if registry is not None else CollectorRegistry()
        self.logger = logger if logger is not None else logging.getLogger("mini_vllm.telemetry")

        self.requests = Counter(
            "mini_vllm_requests_total",
            "Requests accepted by the scheduler.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.finished = Counter(
            "mini_vllm_requests_finished_total",
            "Requests completed by finish reason.",
            ("model", "finish_reason"),
            registry=self.registry,
        )
        self.aborted = Counter(
            "mini_vllm_requests_aborted_total",
            "Requests cancelled before completion.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.preemptions = Counter(
            "mini_vllm_preemptions_total",
            "Sequences preempted because KV-cache capacity was needed.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.prompt_tokens = Counter(
            "mini_vllm_prompt_tokens_total",
            "Prompt tokens accepted by the scheduler.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.generated_tokens = Counter(
            "mini_vllm_generated_tokens_total",
            "Tokens generated by the scheduler.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.prefill_tokens = Counter(
            "mini_vllm_prefill_tokens_total",
            "Tokens processed by prefill, including recompute after preemption.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)

        self.request_duration = Histogram(
            "mini_vllm_request_duration_seconds",
            "Request time from scheduler submission to completion.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.queue_duration = Histogram(
            "mini_vllm_queue_duration_seconds",
            "Time from scheduler submission until first admission.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.ttft = Histogram(
            "mini_vllm_ttft_seconds",
            "Time from scheduler submission until first generated token.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.itl = Histogram(
            "mini_vllm_inter_token_seconds",
            "Time between generated tokens for a sequence.",
            ("model",),
            buckets=_ITL_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.prefill_duration = Histogram(
            "mini_vllm_prefill_duration_seconds",
            "Host-observed duration of a paged prefill call.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.decode_duration = Histogram(
            "mini_vllm_decode_step_duration_seconds",
            "Host-observed duration of a batched decode call.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.scheduler_duration = Histogram(
            "mini_vllm_scheduler_step_duration_seconds",
            "Duration of a complete admit/decode/retire scheduler step.",
            ("model",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        ).labels(model_name)
        self.decode_batch_size = Histogram(
            "mini_vllm_decode_batch_size",
            "Number of sequences in a batched decode call.",
            ("model",),
            buckets=_BATCH_BUCKETS,
            registry=self.registry,
        ).labels(model_name)

        self.waiting_requests = Gauge(
            "mini_vllm_requests_waiting",
            "Requests currently waiting for admission.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.running_requests = Gauge(
            "mini_vllm_requests_running",
            "Requests currently occupying an engine batch slot.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.kv_blocks_free = Gauge(
            "mini_vllm_kv_blocks_free",
            "Unallocated KV-cache blocks.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)
        self.kv_blocks_used = Gauge(
            "mini_vllm_kv_blocks_used",
            "Allocated KV-cache blocks.",
            ("model",),
            registry=self.registry,
        ).labels(model_name)

        self.http_requests = Counter(
            "mini_vllm_http_requests_total",
            "HTTP requests by bounded endpoint and status.",
            ("endpoint", "status"),
            registry=self.registry,
        )
        self.http_duration = Histogram(
            "mini_vllm_http_request_duration_seconds",
            "HTTP handler duration by bounded endpoint.",
            ("endpoint",),
            buckets=_DURATION_BUCKETS,
            registry=self.registry,
        )

    def _log(self, event: str, **fields: Any) -> None:
        self.logger.info(event, extra={"event": event, "telemetry_fields": fields})

    def request_submitted(self, request: Request) -> None:
        self.requests.inc()
        self.prompt_tokens.inc(len(request.prompt_ids))
        self._log(
            "request_submitted",
            request_id=request.request_id,
            model=self.model_name,
            prompt_tokens=len(request.prompt_ids),
            max_new_tokens=request.max_new_tokens,
        )

    def request_admitted(self, request: Request, queue_seconds: float) -> None:
        self.queue_duration.observe(queue_seconds)
        self._log(
            "request_admitted",
            request_id=request.request_id,
            queue_ms=round(queue_seconds * 1000, 3),
        )

    def request_first_token(self, request: Request, ttft_seconds: float) -> None:
        self.ttft.observe(ttft_seconds)
        self._log(
            "request_first_token",
            request_id=request.request_id,
            ttft_ms=round(ttft_seconds * 1000, 3),
        )

    def inter_token_latency(self, seconds: float) -> None:
        self.itl.observe(seconds)

    def tokens_generated(self, count: int) -> None:
        if count:
            self.generated_tokens.inc(count)

    def request_preempted(self, request: Request) -> None:
        self.preemptions.inc()
        self._log(
            "request_preempted",
            request_id=request.request_id,
            preemptions=request.num_preemptions,
        )

    def request_finished(
        self, request: Request, duration_seconds: float, finish_reason: str
    ) -> None:
        self.finished.labels(self.model_name, finish_reason).inc()
        self.request_duration.observe(duration_seconds)
        self._log(
            "request_finished",
            request_id=request.request_id,
            duration_ms=round(duration_seconds * 1000, 3),
            generated_tokens=len(request.generated_ids),
            finish_reason=finish_reason,
            preemptions=request.num_preemptions,
        )

    def request_aborted(self, request: Request, duration_seconds: float) -> None:
        self.aborted.inc()
        self._log(
            "request_aborted",
            request_id=request.request_id,
            duration_ms=round(duration_seconds * 1000, 3),
            generated_tokens=len(request.generated_ids),
        )

    def prefill_completed(self, token_count: int, duration_seconds: float) -> None:
        self.prefill_tokens.inc(token_count)
        self.prefill_duration.observe(duration_seconds)

    def decode_completed(self, batch_size: int, duration_seconds: float) -> None:
        self.decode_batch_size.observe(batch_size)
        self.decode_duration.observe(duration_seconds)

    def scheduler_initialized(self, total_blocks: int) -> None:
        self.waiting_requests.set(0)
        self.running_requests.set(0)
        self.kv_blocks_free.set(total_blocks)
        self.kv_blocks_used.set(0)

    def scheduler_step(self, snapshot: SchedulerSnapshot) -> None:
        self.waiting_requests.set(snapshot.waiting_requests)
        self.running_requests.set(snapshot.running_requests)
        self.kv_blocks_free.set(snapshot.free_blocks)
        self.kv_blocks_used.set(snapshot.used_blocks)
        self.scheduler_duration.observe(snapshot.step_duration_seconds)

    def http_request(self, endpoint: str, status: int, duration_seconds: float) -> None:
        """Record only normalized endpoints; never use raw paths as labels."""

        self.http_requests.labels(endpoint, str(status)).inc()
        self.http_duration.labels(endpoint).observe(duration_seconds)

    def metrics_app(self):
        return make_asgi_app(registry=self.registry)
